/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet; 
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel; 
import controller.c_koneksi; 
import controller.controllerToko; 
import model.m_toko;  


/**
 *
 * @author Salsadila
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();

    /**
     * Creates new form login
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }
    public JTextField getTxtKode(){      
        return TxtKode; 
    }
    public JTextField getTxtNama(){   
        return TxtNama;   
    }
    public JTextField getTxtHarga(){   
        return TxtHarga;   
    } 
    public JComboBox getCbKategori(){   
        return CbKategori;
    }
    public JComboBox getCbJenis(){
        return CbJenis;   
    }
    public JComboBox getCbCariKategori(){    
        return CbCariKategori; 
    }
    public JButton getButtonHapus(){    
        return BtnHapus;  
    }   
    public JButton getButtonBersih(){  
        return BtnBersih;  
    }
    public JButton getButtonSimpan(){   
        return BtnSimpan;  
    } 
    public JButton getButtonUbah(){ 
        return BtnUbah;  
    }
    public JButton getButtonKeluar(){   
        return BtnKeluar; 
    }
    public JTable getTableData(){    
        return Tabel1;    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtHarga = new javax.swing.JTextField();
        TxtKode = new javax.swing.JTextField();
        CbCariKategori = new javax.swing.JComboBox<>();
        CbKategori = new javax.swing.JComboBox<>();
        TxtNama = new javax.swing.JTextField();
        BtnUbah = new javax.swing.JButton();
        BtnBersih = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnCari = new javax.swing.JButton();
        BtnSimpan = new javax.swing.JButton();
        CbJenis = new javax.swing.JComboBox<>();
        BtnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        txtadmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(TxtHarga);
        TxtHarga.setBounds(100, 210, 260, 30);
        getContentPane().add(TxtKode);
        TxtKode.setBounds(100, 90, 260, 30);

        CbCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Kebersihan", "Pakaian", "Kecantikan" }));
        getContentPane().add(CbCariKategori);
        CbCariKategori.setBounds(240, 270, 120, 30);

        CbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Kebersihan", "Pakaian", "Kecantikan" }));
        getContentPane().add(CbKategori);
        CbKategori.setBounds(100, 150, 260, 30);
        getContentPane().add(TxtNama);
        TxtNama.setBounds(100, 120, 260, 30);

        BtnUbah.setText("Ubah");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUbah);
        BtnUbah.setBounds(410, 120, 100, 30);

        BtnBersih.setText("Bersihkan");
        BtnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBersihActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBersih);
        BtnBersih.setBounds(410, 150, 100, 30);

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHapus);
        BtnHapus.setBounds(410, 180, 100, 30);

        BtnCari.setText("Cari");
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCari);
        BtnCari.setBounds(410, 270, 100, 30);

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSimpan);
        BtnSimpan.setBounds(410, 90, 100, 30);

        CbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Botol", "Plastik", "Kardus", "Sterofoam" }));
        getContentPane().add(CbJenis);
        CbJenis.setBounds(100, 180, 260, 30);

        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeluar);
        BtnKeluar.setBounds(410, 210, 100, 30);

        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        jScrollPane2.setViewportView(Tabel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(12, 320, 520, 130);

        txtadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadminActionPerformed(evt);
            }
        });
        getContentPane().add(txtadmin);
        txtadmin.setBounds(100, 10, 80, 30);

        jLabel1.setText("Pencarian Berdasarkan Kategori Makanan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 270, 230, 30);

        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 80, 30);

        jLabel3.setText("Kategori Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 80, 30);

        jLabel4.setText("Jenis Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 180, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Data Barang di Toko");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 50, 150, 30);

        jLabel6.setText("Admin Toko :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 80, 30);

        jLabel7.setText("Kode Barang");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 90, 80, 30);

        jLabel8.setText("Harga");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 210, 80, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\pic\\0fb9e438bf292df2141c58fe0751ebd1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-40, -10, 650, 520);

        setBounds(0, 0, 556, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        // TODO add your handling code here:
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_BtnUbahActionPerformed

    private void BtnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBersihActionPerformed
        // TODO add your handling code here:
        ctoko.Reset();
    }//GEN-LAST:event_BtnBersihActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        // TODO add your handling code here:
        ctoko.CariKategori();
        ctoko.isiTable();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user1 = login.user;
        txtadmin.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    private void txtadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBersih;
    private javax.swing.JButton BtnCari;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> CbCariKategori;
    private javax.swing.JComboBox<String> CbJenis;
    private javax.swing.JComboBox<String> CbKategori;
    private javax.swing.JTable Tabel1;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtKode;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtadmin;
    // End of variables declaration//GEN-END:variables

   
}
